USE [master]
GO

if exists (select * from sysdatabases where name='MegaDb')
		drop database MegaDb
GO

DECLARE @device_directory NVARCHAR(520)
SELECT @device_directory = SUBSTRING(filename, 1, CHARINDEX(N'master.mdf', LOWER(filename)) - 1)
FROM master.dbo.sysaltfiles WHERE dbid = 1 AND fileid = 1

EXECUTE (N'CREATE DATABASE MegaDb
  ON PRIMARY (NAME = N''MegaDb'', FILENAME = N''' + @device_directory + N'megadb.mdf'')
  LOG ON (NAME = N''MegaDb_log'',  FILENAME = N''' + @device_directory + N'megadb.ldf'')')
GO

ALTER DATABASE [MegaDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MegaDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MegaDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MegaDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MegaDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MegaDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MegaDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [MegaDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MegaDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MegaDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MegaDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MegaDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MegaDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MegaDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MegaDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MegaDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MegaDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MegaDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MegaDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MegaDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MegaDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MegaDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MegaDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MegaDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MegaDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MegaDb] SET  MULTI_USER 
GO
ALTER DATABASE [MegaDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MegaDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MegaDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MegaDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MegaDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MegaDb] SET QUERY_STORE = OFF
GO
USE [MegaDb]
GO
/****** Object:  Table [dbo].[Items]    Script Date: 12/16/2019 6:24:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Items](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[LocationID] [int] NOT NULL,
	[ManufacturerID] [int] NOT NULL,
 CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 12/16/2019 6:24:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Locations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Manufacturers]    Script Date: 12/16/2019 6:24:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Manufacturers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Manufacturers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Items]    Script Date: 12/16/2019 6:24:54 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Items] ON [dbo].[Items]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Items_Location]    Script Date: 12/16/2019 6:24:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_Items_Location] ON [dbo].[Items]
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Items_Manufacturer]    Script Date: 12/16/2019 6:24:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_Items_Manufacturer] ON [dbo].[Items]
(
	[ManufacturerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Locations]    Script Date: 12/16/2019 6:24:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_Locations] ON [dbo].[Locations]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Manufacturers]    Script Date: 12/16/2019 6:24:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_Manufacturers] ON [dbo].[Manufacturers]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK_Items_Locations] FOREIGN KEY([LocationID])
REFERENCES [dbo].[Locations] ([Id])
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK_Items_Locations]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK_Items_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([Id])
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK_Items_Manufacturers]
GO

INSERT [dbo].[Locations] ([Name]) VALUES (N'Aisle 1')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Aisle 2')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Aisle 3')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Aisle 4')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Aisle 5')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Produce')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Dairy')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Meat')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Deli')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Bakery')
GO
INSERT [dbo].[Locations] ([Name]) VALUES (N'Seafood')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Kraft')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Western Family')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Generic')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Amazon')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Sam''s Choice')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Great Value')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Kroger')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Albertsons')
GO
INSERT [dbo].[Manufacturers] ([Name]) VALUES (N'Homestyle')
GO
USE [master]
GO
ALTER DATABASE [MegaDb] SET  READ_WRITE 
GO